credentials:
  usernames:
    kintscher:
      email: marcel.kintscher@claudyconsulting.com
      name: Marcel Kintscher
      password: 'kinya1997'
    philippe:
      email: philippe.fuhrer@hotmail.com
      name: Philippe Fuhrer
      password: 'philya1919'
cookie:
  expiry_days: 10
  key: xejcwcbz34648bfcez637
  name: fifafifapredictionscookie
preauthorized:
  emails:
  - philippe.fuhrer@hotmail.com